#!/bin/bash
##############################################################
# the name of job
#PBS -N crc
# set the queue
#PBS -q Biocc.Li

# nodes: number of nodes requested by job
# ppn  : the number of processors per node requested by job
#PBS -l nodes=1:ppn=1

#PBS -l walltime=1000:00:00
##############################################################
source activate /bioXJ/zhouww/0_tools_donotdel/scenic_zww
cd /bioXJ/zhouww/SCENIC/scRNA/4_cancer_gene_wilcox/code/
python crc_wilcox.py